In [30]:
import pandas as pd

In [31]:
data = {
    "name": ["Nate", "John", "Jane", "Manday"],
    "age": [39, 23, 31, 25],
    "sex": ["m", "m", "f", "f"],
    "email": ["nate@gmail.com", "john@gmail.com", "jane@gmail.com", "mandy@gmail.com"],
    "purchases": [34, 12, 42, 8],
}

df = pd.DataFrame(data=data)
df

     name  age sex            email  purchases
0    Nate   39   m   nate@gmail.com         34
1    John   23   m   john@gmail.com         12
2    Jane   31   f   jane@gmail.com         42
3  Manday   25   f  mandy@gmail.com          8

In [32]:
df = df.rename(columns={"sex": "gender"})
df

     name  age gender            email  purchases
0    Nate   39      m   nate@gmail.com         34
1    John   23      m   john@gmail.com         12
2    Jane   31      f   jane@gmail.com         42
3  Manday   25      f  mandy@gmail.com          8

In [33]:
df["active"] = True
df

     name  age gender            email  purchases  active
0    Nate   39      m   nate@gmail.com         34    True
1    John   23      m   john@gmail.com         12    True
2    Jane   31      f   jane@gmail.com         42    True
3  Manday   25      f  mandy@gmail.com          8    True

In [34]:
df[["name", "email"]]

     name            email
0    Nate   nate@gmail.com
1    John   john@gmail.com
2    Jane   jane@gmail.com
3  Manday  mandy@gmail.com

In [35]:
df["purchases"] = df["purchases"] + 5
df

     name  age gender            email  purchases  active
0    Nate   39      m   nate@gmail.com         39    True
1    John   23      m   john@gmail.com         17    True
2    Jane   31      f   jane@gmail.com         47    True
3  Manday   25      f  mandy@gmail.com         13    True

In [36]:
df.loc[df["purchases"] > 20]

   name  age gender           email  purchases  active
0  Nate   39      m  nate@gmail.com         39    True
2  Jane   31      f  jane@gmail.com         47    True

In [37]:
hash = {
    "m": "male",
    "f": "female"
}

df["gender"] = df["gender"].replace(hash)
df

     name  age  gender            email  purchases  active
0    Nate   39    male   nate@gmail.com         39    True
1    John   23    male   john@gmail.com         17    True
2    Jane   31  female   jane@gmail.com         47    True
3  Manday   25  female  mandy@gmail.com         13    True